### ISSUE TITLE
the app does not find the headphones

### ISSUE THREAD

**Issue by grudshow** [steam3d/MagicPods-Windows#276] opened 2022-12-15 08:48 UTC
![image](https://user-images.githubusercontent.com/31015135/207814326-c92909da-4573-4e71-91cb-c1dfdcf2813b.png)

**Comment by steam3d** [comment] 2022-12-25 13:49
Hi. Open the MagicPods on support page. Click 5-10 time on MagicPods logo while page do not refresh. Then go to General Settings scroll down and change Log level to Debug or Trace. Restart the app.

Open the MagicPods again and go to support page, click on debug log and upload log files here.

**Comment by AlexDT** [comment] 2022-12-27 16:03
@steam3d I have a similar issue: 
What problems can you derive from my logs?
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10309493/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10309494/MagicPodsUILog.txt)

**Comment by steam3d** [comment] 2022-12-27 16:10
@AlexDT Manually update MagicPods

![image](https://user-images.githubusercontent.com/30986874/209692200-2786826d-9d88-4ae9-954b-27da34e78f50.png)

**Comment by steam3d** [comment] 2022-12-27 16:17
Fixed in 2.0.38.0 update.

**Closed by steam3d** 2022-12-27 16:17 UTC

**Comment by AlexDT** [comment] 2022-12-27 16:30
Thanks I will check the update. I am not issue starter btw.

**Comment by steam3d** [comment] 2022-12-27 16:39
@AlexDT We discussed your issue [here](https://github.com/steam3d/MagicPods-Windows/issues/280). You can read what the problem is. I am just closing issues because I released update today.

**Comment by AlexDT** [comment] 2022-12-27 17:55
@steam3d Update solved the issue for me! Thanks.
